### ISSUE TITLE
Java 10: NoSuchFieldException: handle

### ISSUE THREAD

**Issue by jo5ef** [vert-x3/vertx-embedded-mongo-db#8]
Using Java 10 (oracle) the following exception is thrown when using embedded mongo and also when running the tests of this project:

```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2370)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:109)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:51)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$2.getPid(Processes.java:209)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:64)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
	at io.vertx.ext.embeddedmongo.EmbeddedMongoVerticle.start(EmbeddedMongoVerticle.java:87)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:308)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

But even with this exception in the log it works as expected as far as I can tell.

**Comment by vietj** [comment]
@jo5ef can you report it here https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues and link the issue ?

**Comment by vietj** [comment]
@jo5ef for the record, we plan to drop embedded mongo of vert.x after 3.x as we believe we don't need such service

**Comment by jo5ef** [comment]
Ok, I'll report it there too. I also prefer appropriate testing capabilities in the driver instead so I'm happy with your decision to drop it : )

**Comment by karianna** [comment]
Closing as this is an upstream issue.
